apiVersion: v1
kind: Service
metadata:
  name: ums-service
  namespace: backend
spec:
  selector:
    app: ums

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP
