apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-deployment
  namespace: backend
  labels:
    app: tms
    team: paves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tms
    spec:
      serviceAccountName: paves-service-account
      containers:
        - name: tms
          image: 743737183908.dkr.ecr.ap-south-1.amazonaws.com/paves/tms-dev:dev-60cfe57
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: tms-secrets
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/tms"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "768Mi"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
