apiVersion: v1
kind: Service
metadata:
  name: tms-service
  namespace: backend
  labels:
    app: tms
    team: paves
spec:
  selector:
    app: tms
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
