apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    app.kubernetes.io/managed-by: paves
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    app.kubernetes.io/managed-by: paves
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/managed-by: paves
    environment: dev
