apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paves-tms
  namespace: argocd
  labels:
    team: paves
spec:
  project: default
  source:
    repoURL: https://github.com/PavesTechnologies/intranet-devops
    targetRevision: dev
    path: k8s/backend/tms
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
