apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-deployment
  namespace: backend
  labels:
    app: lms
    team: paves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lms
    spec:
      serviceAccountName: paves-service-account
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: lms
          image: 743737183908.dkr.ecr.ap-south-1.amazonaws.com/paves/lms-prod:prod-f4fae76
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          envFrom:
            - secretRef:
                name: lms-secrets
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/lms"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
