apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: debezium-rds-secret
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: debezium-rds-secret
    creationPolicy: Owner
  data:
    - secretKey: db_host
      remoteRef:
        key: prod-eos        # ← your actual AWS secret name
        property: DB_HOST   # ← exact field name in AWS secret

    - secretKey: db_user
      remoteRef:
        key: prod-eos
        property: DB_USER   # ← exact field name in AWS secret

    - secretKey: db_password
      remoteRef:
        key: prod-eos
        property: DB_PASSWORD  # ← exact field name in AWS secret
