apiVersion: v1
kind: ServiceAccount
metadata:
  name: paves-service-account
  namespace: backend
  labels:
    app.kubernetes.io/managed-by: paves
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paves-service-account
  namespace: infra
  labels:
    app.kubernetes.io/managed-by: paves
